### ISSUE TITLE
how to search a note ?

### ISSUE THREAD

**Issue by yuxuangu** [CSC207-UofT/course-project-group_nib#5]
how to search a note on our database if we want to search and modify or comment on an existing file? need some help.

**Comment by zhangchengyue** [comment]
I think we can let the user to type in the title of the note (we are assuming that they know exactly which note they want to search for.) and then search whether that title exists in our database.  We can create a hash map which includes all the notes, and then use its containsKey("Note Title") to search for the specific note. 

This is just my own opinion.
